@baseUrl = https://localhost:7276

### Get Vehicle Details
GET {{baseUrl}}/api/vehicles/LB11WXA
Accept: application/json

### Get Vehicle Details (with spaces)
GET {{baseUrl}}/api/vehicles/LB11%20WXA
Accept: application/json

### Get Vehicle Details (invalid)
GET {{baseUrl}}/api/vehicles/INVALID
Accept: application/json

### Get Vehicle Details (empty)
GET {{baseUrl}}/api/vehicles
Accept: application/json

### Response Examples
# Success Response:
# {
#   "registration": "LB11WXA",
#   "make": "KIA",
#   "model": "RIO",
#   "colour": "SILVER",
#   "motExpiryDate": "2024-01-01T00:00:00",
#   "mileageAtLastMot": 97000
# }
#
